### ISSUE TITLE
feature: Cache Adapters

### ISSUE THREAD

**Issue by DjDeveloperr** [discord-deno/discord.deno#16]
There can be some sort of Cache Adapters which Client can use to handle caching. Those adapters can implement the basic methods we require for caching, like it can be similar to a Map with set, get, delete, and  so on. In this way, there can even be persistent caching using something like Redis, just an adapter, which can be a class implementing an interface, will be needed.

**Comment by Helloyunho** [comment]
Thanks for your opinion! I'll definitely try to implement that!

**Comment by DjDeveloperr** [comment]
Trying to implement this myself 😅 If I'm able to do it, I'll Pull Request the changes.
