### ISSUE TITLE
TODO: Simplify Intents

### ISSUE THREAD

**Issue by DjDeveloperr** [discord-deno/discord.deno#26]
Intents are kind of messed up for beginners, we need to mention a large Array of these, as of the test/index,ts, for a bot with both intents enabled:
```ts
client.connect(TOKEN, [
  GatewayIntents.GUILD_MEMBERS,
  GatewayIntents.GUILD_PRESENCES,
  GatewayIntents.GUILD_MESSAGES,
  GatewayIntents.DIRECT_MESSAGES,
  GatewayIntents.DIRECT_MESSAGE_REACTIONS,
  GatewayIntents.DIRECT_MESSAGE_TYPING,
  GatewayIntents.GUILDS,
  GatewayIntents.GUILD_BANS,
  GatewayIntents.GUILD_EMOJIS,
  GatewayIntents.GUILD_INTEGRATIONS,
  GatewayIntents.GUILD_INVITES,
  GatewayIntents.GUILD_MESSAGE_REACTIONS,
  GatewayIntents.GUILD_MESSAGE_TYPING,
  GatewayIntents.GUILD_VOICE_STATES,
  GatewayIntents.GUILD_WEBHOOKS
])
```

This can be simplified by making some class with static properties like, Intents.All, Intents.Presence, Intents.ServerMembers, would be a lot helpful.
...and I'll look into doing this with my next PR 😄 If I'm wrong, please correct me.

**Comment by Helloyunho** [comment]
Those things were going to be in this project but somehow I forgot

Thanks for letting me know again!
