### ISSUE TITLE
ESLint should be enforced with Actions 

### ISSUE THREAD

**Issue by TorchedSammy** [discord-deno/discord.deno#28]
https://github.com/discord-deno/discord.deno/pull/27#discussion_r518713288
After looking at this I also saw there wasn't any GitHub Actions to actively enforce style on PRs, pushes, etc. and I think you should setup one.

If you need an example I can post one.

**Comment by Helloyunho** [comment]
Hi! Why yes, I was thinking of that but I didn't know how to do it (and also too lazy to do it) so I didn't. If you can give me an example, it'll be great!

**Comment by TorchedSammy** [comment]
[lint.yml from my AnsiKit library](https://github.com/Luvella/AnsiKit/blob/master/.github/workflows/lint.yml)
May (not) need to do more for typescript

**Comment by Helloyunho** [comment]
Fixed from 9209240602b58d68b4838aa280b5714692bdc647. Thanks!
